### ISSUE TITLE
roadmap questions

### ISSUE THREAD

**Issue by hannesm** [tarides/ocaml-platform-roadmap#1]
Dear Madam or Sir,

I have some questions:
1. Is "reproducible builds" part of the roadmap (as defined by https://reproducible-builds.org/)? If no, why not?
2. Do you have plans for "supply chain security"?
3. I don't quite get the (W12) "Compile to MirageOS" - did you investigate the build principal of a MirageOS unikernel, and have ideas how to achieve this with `dune build -x mirage`?
4. In (W23) you mention "gospel", but there seems to be other formal verification tools out there (Coq, ...) -- is there any plan? Or is the interest to only pick gospel (for which reasons?)?
5. In (W27) you talk about installers - this has a broad scope, what is the incentive? Do you plan to enable generating packages (debian/ ...) for each opam package - that are suitable to be upstreamed to the debian repository / .. ? Or do you plan to provide one-off packages to be distributed separately?

In several places, it would be good to acknowledge prior work (in the OCaml ecosystem) on different workflows.
To point out an example, for W27 there are several tools available: opam-bin / albatross shell scripts / using orb to capture reproducibility and source information.

**Comment by tmattio** [comment]
Hi @hannesm,

Thanks for your (excellent!) questions :)

> * Is "reproducible builds" part of the roadmap (as defined by https://reproducible-builds.org/)? If no, why not?

To establish the roadmap, we adopted a data-driven and user-centric approach. In addition to aggregating the input of the maintainers of the Platform projects, we analysed the results of the OCaml surveys; reviewed blog posts and Discuss posts that contained feedback on OCaml user experience; we interviewed OCaml developers (both industrial users and individual developers); and we [iterated on drafts of the roadmap in public](https://discuss.ocaml.org/t/a-roadmap-for-the-ocaml-platform-seeking-your-feedback/12238) to gather community feedback.

In this process, we didn't get much feedback on reproducible builds, and it didn't appear as something that is hurting developer experience or adoption, so it didn't make its way into the roadmap.

That said, as I mentioned in the [announcement](https://discuss.ocaml.org/t/the-ocaml-platform-roadmap-is-adopted/13459), the roadmap is a living document, and it's expected to change as OCaml tooling development continues in the coming years. If you think reproducible builds should be in the roadmap, I'm happy to discuss this together and work towards editing the roadmap to encompass this.

> * Do you have plans for "supply chain security"?

No, for the same reason as above.

> * I don't quite get the (W12) "Compile to MirageOS" - did you investigate the build principal of a MirageOS unikernel, and have ideas how to achieve this with `dune build -x mirage`?

The Dune team had some ideas of how to achieve this yes. I should note that the roadmap is not intended as a definite design spec for the workflows, but more as a guideline for the developer experience. The specific commands are suggestive. At the end of the day, it's up to maintainers of the project to define how the feature is designed, and that wasn't part of the roadmap.

The intent of this workflow is to say that Dune users should be able to build Mirage unikernels without using a separate tool. I expect that we'll see an RFC for how to achieve that exactly when work starts on this.

> * In (W23) you mention "gospel", but there seems to be other formal verification tools out there (Coq, ...) -- is there any plan? Or is the interest to only pick gospel (for which reasons?)?

By the nature of the goal of the project, I believe Gospel is particularly well suited to integrating formal verification practices into normal OCaml development workflows, but there's no intention to pick Gospel in particular if other tools appear to be better alternatives. There's also no fundamental reason for not supporting multiple tools (although it might not be practical).

> * In (W27) you talk about installers - this has a broad scope, what is the incentive? Do you plan to enable generating packages (debian/ ...) for each opam package - that are suitable to be upstreamed to the debian repository / .. ? Or do you plan to provide one-off packages to be distributed separately?

I think there's room for both, and that in practice they overlap significantly. The motivation behind this workflow is that distributing OCaml applications to users is currently challenging, and that makes OCaml a difficult choice for developers who ship applications to end-users. However, because there is a larger user base, I figure that building installers for Windows and macOS is a higher priority than Linux distributions or other operating systems.

> In several places, it would be good to acknowledge prior work (in the OCaml ecosystem) on different workflows.
> To point out an example, for W27 there are several tools available: opam-bin / albatross shell scripts / using orb to capture reproducibility and source information.

Agreed. I'll be on the lookout for those, but please don't hesitate to send a PR to https://github.com/ocaml/ocaml.org if you see that a workflow is lacking appropriate acknowledgement of prior work.

**Comment by hannesm** [comment]
Thanks for your reply, I don't want to repeat myself. Feel free to re-read https://discuss.ocaml.org/t/ann-ocaml-platform-installer-alpha-release/10652/4

My point of view is rather different -- I care more about OCaml binaries being distributed (secure, trustworthy, with an upgrade path) than on the developer experience (which is important as well). At some point a developer wants to ship binaries (of course your mileage may vary).

**Comment by hannesm** [comment]
Anyways, I'm closing this issue. Good luck with your platform roadmap.
